<?xml version="1.0"?>
<package format="3">
  <name>lds_json_replay</name>
  <version>0.1.0</version>
  <description>Replay LDS JSON files as ROS 2 LaserScan messages.</description>
  <maintainer email="obloodobladeo@gmail.com">kim</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rosbridge_server</exec_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>turtlebot3_gazebo</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
